"""frontmatter_check.py -- deterministic judge for vault frontmatter hygiene.

Counts .md files missing valid frontmatter (--- block + tags/status/created/
privacy + status in VALID_STATUS). Exit code 0 = zero failures.

Designed as the exit condition for autonomous loops (see docs/autonomous-loops.md)
and as the nightly hygiene scanner's source of truth: the same judge that gates
the loop also decides what the night shift reports, so nothing gets re-reported.

Configure via env:
  VAULT_ROOT  -- vault path (default: current directory)
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

VAULT = Path(os.environ.get("VAULT_ROOT", "."))

# Never scanned: code, caches, autogenerated queues, external tooling
EXCLUDE_DIRS = (
    ".obsidian/", ".trash/", ".git/", ".github/", ".claude/",
    "node_modules/", ".pytest_cache/", "__pycache__/", ".venv/",
    "_private/tmp/", "_tasks/",
)

# Code-convention files, not vault notes
SKIP_NAMES = {"README.md", "LICENSE.md", "CHANGELOG.md", "CONTRIBUTING.md",
              "CLAUDE.md", "SETUP.md", "ARCHITECTURE.md", "MEMORY.md", "USER.md"}

REQUIRED = ("tags", "status", "created", "privacy")
VALID_STATUS = {"draft", "active", "review", "done", "archived"}

FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*(\n|\Z)", re.DOTALL)


def check_file(path: Path) -> list[str]:
    """Returns a list of failures for one file (empty = OK)."""
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError) as e:
        return [f"unreadable: {e.__class__.__name__}"]

    if "﻿" in text:
        # A BOM (leading or embedded) hides frontmatter from parsers and has
        # caused double-block corruption when fixers prepend a new block on
        # top of a hidden one. Always a failure.
        return ["contains BOM (UTF-8 must be BOM-free)"]

    m = FM_RE.match(text)
    if not m:
        return ["missing frontmatter block"]

    fm = m.group(1)
    errors = []
    for field in REQUIRED:
        if not re.search(rf"^{field}\s*:", fm, re.MULTILINE):
            errors.append(f"missing field: {field}")

    sm = re.search(r"^status\s*:\s*(\S+)", fm, re.MULTILINE)
    if sm:
        status = sm.group(1).strip().strip('"').strip("'")
        if status not in VALID_STATUS:
            errors.append(f"invalid status: {status}")
    return errors


def main() -> int:
    failures: dict[str, list[str]] = {}
    for path in sorted(VAULT.rglob("*.md")):
        rel = path.relative_to(VAULT).as_posix()
        if any(rel.startswith(part) or f"/{part}" in f"/{rel}" for part in EXCLUDE_DIRS):
            continue
        if path.name in SKIP_NAMES:
            continue
        errors = check_file(path)
        if errors:
            failures[rel] = errors

    print(f"FAILURES: {len(failures)}")
    for rel, errors in failures.items():
        print(f"- {rel}: {'; '.join(errors)}")
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
